language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6


env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source
  - mysql -e 'create database melifarobooking;'
  - php Tests/Fixtures/app/console doctrine:schema:drop --force
  - php Tests/Fixtures/app/console doctrine:schema:create
  - php Tests/Fixtures/app/console doctrine:fixtures:load --fixtures="Tests/Fixtures/Data/" -n

notifications:
  email: iakov@codeforges.com
